version: "2"

volumes:
  node_data:
  client_data:

services:
  node:
    image: tezos/tezos:v7.1
    container_name: tezos-node
    hostname: node
    command: tezos-node --network carthagenet
    ports:
      - '9732:9732'
      - '127.0.0.1:8732:8732'
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: always
  exporter:
    image: node:alpine
    container_name: exporter-node
    hostname: exporter
    command: node proxy.js
    working_dir: /src
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - .:/src
    restart: always
